### ISSUE TITLE
Switch dependency order for ConditionallyAssignable and ConditionallySelectable generics

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/subtle#10]
Right now, we have `impl<T> ConditionallySelectable for T where T: Copy + ConditionallyAssignable`, but instead we should have a generic implementation of `impl<T> ConditionallyAssignable for T where T: Copy + ConditionallySelectable`.

**Comment by hdevalence** [comment]
This is fixed by #12. Thanks @saleemrashid!
