### ISSUE TITLE
error: "the name `black_box` is defined multiple times" when feature `core_hint_black_box` enabled

### ISSUE THREAD

**Issue by madadam** [dalek-cryptography/subtle#126]
Just what the title says : when feature `core_hint_black_box` is enabled, compilation of this crate fails because it unconditionally defines its own `black_box`: https://github.com/dalek-cryptography/subtle/blob/main/src/lib.rs#L223

**Comment by isislovecruft** [comment]
Hi @madadam! Thanks for alerting us to this. I've just released 2.6.1 which should fix the issue.
