### ISSUE TITLE
Tag 2.6.1 and add it to changelog

### ISSUE THREAD

**Issue by martinvonz** [dalek-cryptography/subtle#128]
Both 2.6.0 and 2.6.1 are missing from the changelog, and 2.6.1 is missing a tag. That makes it harder to figure out what the reason for the yanked 2.6.0 was.

**Comment by isislovecruft** [comment]
Hi @martinvonz! The tag for 2.6.0 looks like it was already pushed. Thanks for pointing out that 2.6.1 was missing; I just pushed it.

2.6.0 was yanked due to #125, there were no major issues other than the buiid error with certain configuration flags.

**Comment by martinvonz** [comment]
Thanks! Do you mind updating the changelog too?
