### ISSUE TITLE
License notices inconsistent; CC0 or 3-clause BSD?

### ISSUE THREAD

**Issue by joshtriplett** [dalek-cryptography/subtle#19]
The comments in the code itself state the license as a CC0 public domain dedication, but `Cargo.toml` and `LICENSE` give the license as 3-clause BSD. Which one is the code licensed under?

**Comment by isislovecruft** [comment]
Hi! Sorry for the confusion. It's 3-clause BSD. The CC0 licenses are from the pre-released version.. I'll go fix that.
