### ISSUE TITLE
Why does the generic impl for ConditionallyAssign require a Copy bound?

### ISSUE THREAD

**Issue by Pratyush** [dalek-cryptography/subtle#23]
From what I understand, this line doesn't require `Copy` at all:

https://github.com/dalek-cryptography/subtle/blob/285d276f208544585784d2ba010ea953a129a889/src/lib.rs#L395

Removing the copy bound still compiles and all tests pass.

**Comment by hdevalence** [comment]
Cool find, I suspect that the `Copy` bound may have been left over from when we had a reversed implication of which traits implied which.

**Comment by isislovecruft** [comment]
Fixed in #27
