### ISSUE TITLE
Provide impls of Conditionally{Assign, Negate, Swap} for integer types when generic-impls is not selected

### ISSUE THREAD

**Issue by Pratyush** [dalek-cryptography/subtle#24]
When `generic-impls` is not selected, `Conditionally{Assign, Negate, Swap}` are not implemented for the integer types. The traits also can't be implemented by downstream traits because of the orphan rules. Therefore, I think it makes sense to have impls of these traits for the integer types behind a `#[cfg(not(feature = "generic-impls"))]` flag.

**Comment by hdevalence** [comment]
This probably now depends on discussion in #25, crossreferencing to there

**Comment by isislovecruft** [comment]
This should be fixed by #29.
