### ISSUE TITLE
i128 feature gate

### ISSUE THREAD

**Issue by newpavlov** [dalek-cryptography/subtle#28]
I plan to use `subtle` instead of `constant_time_eq` in RustCrypto. But I would like to keep to support Rust 1.21 for now. So it would be nice if you'll add enabled-by-default `i128` feature gate.

P.S.: CI tests for MSRV would be nice as well.

**Comment by hdevalence** [comment]
MSRV?

**Comment by newpavlov** [comment]
Ah, sorry, it's an abbreviation for [Minimum Supported Rust Version](https://github.com/rust-lang/rfcs/pull/2495).

**Comment by hdevalence** [comment]
Ah, great, thanks! Until now we've just been aiming for "always latest stable", but for no real reason. I'll take a look, then file some issues.
