### ISSUE TITLE
Clarify "root traits" - ConditionallySelectable and ConstantTimeEq

### ISSUE THREAD

**Issue by cathieyun** [dalek-cryptography/subtle#36]
The subtle "root traits" are supposed to be `ConditionallySelectable` and `ConstantTimeEq`, and all other traits are supposed to be implemented based on those. Clarify that this should be the case in the docs.

This should help prevent situations where a struct implements `ConditionallyAssignable`, for instance, but not `ConditionallySelectable`, such as here:
https://github.com/dalek-cryptography/curve25519-dalek/issues/200

**Comment by isislovecruft** [comment]
We now have this in `2.0.0-pre.0`.

Perhaps though we could still use some sort of "How To Use This Crate" section?

**Comment by hdevalence** [comment]
Closing since it's fixed in 2.0.0-pre.0.
