### ISSUE TITLE
Switch to `hint::black_box` when it becomes available

### ISSUE THREAD

**Issue by hdevalence** [dalek-cryptography/subtle#37]
Tracking issue: https://github.com/rust-lang/rfcs/pull/2360

Previous suggestions for `black_box` (like volatile read/write) wouldn't work, because we want to be able to use `Choice`s in hot loops, and adding overhead makes that harder.  However, the proposed `hint::black_box` should work for us and will let us have timing protections on stable Rust (if/when it's stabilized).

**Comment by RalfJung** [comment]
Notice that using optimization *hints* for security *guarantees* is... slippery territory at best.

Is there a way to get the timing protection you want in LLVM, i.e., something that LLVM *documents* will have the effect you want? If no, I'm afraid Rust cannot really provide any guarantees itself, and it'd probably be an interesting but non-trivial project to get such guarantees into LLVM. If yes, it'd be great if you could write an RFC to expose that functionality on the Rust side :) .

**Comment by hdevalence** [comment]
Thanks for the concern.  As noted in the documentation, this crate provides best-effort protections, not security guarantees (which are impossible to provide in software, for the reasons described in the documentation).  The optimization hint is used, not to provide general timing guarantees, but to guard against a specific optimization.

There is work to provide constant-time conditional move / conditional select intrinsics with in LLVM, and we'd like to use them if and when they become available, but that's a distinct issue from this one (we don't use `black_box` for that purpose), and one that's on a longer time horizon.

**Comment by jethrogb** [comment]
In its current implementation `core::hint::black_box` creates a pointer to the input value. This is required in `core` since it takes `T` which could be any size. In #49 I'm proposing not doing that, which generates better code. Switching back to `core::hint::black_box` after that lands would be unfortunate. It would be great if Rust's `black_box` were implemented in terms of some LLVM intrinsic that doesn't required putting things in memory.

**Comment by hdevalence** [comment]
Closing this after #49, #54
