### ISSUE TITLE
Constant-time Option<T>

### ISSUE THREAD

**Issue by str4d** [dalek-cryptography/subtle#39]
Currently, when taking a variable-time function that returns `Option<T>` and making it constant-time, you need to return `(Choice, T)` and then require that the caller checks the `Choice` before using the result. It would be safer to wrap this as `CTOption<T>(Choice, T)`, and then provide equivalent `is_none()`, `is_some()` functions that check the `Choice`, and an `unwrap()` function that panics if the `Choice` is false.

This could also possibly provide `CTOption<T>::ct_map()`, by computing the map function over the internal `T` regardless of the value of `Choice` (with the result still being restricted by the API).

**Comment by ebfull** [comment]
Having thought about `ct_map` more, I'm a little worried about the undefined state of the internal value. You could use the `FnOnce` to sneak the value out of the scope. @hdevalence's suggestion that it be bounded as `Default` seems like a potential fix for that problem.

**Comment by hdevalence** [comment]
Closed by #40.
