### ISSUE TITLE
Allow for constructing a constant Choice

### ISSUE THREAD

**Issue by ebfull** [dalek-cryptography/subtle#52]
`Choice` doesn't provide a `const fn` for constructing the `Choice`, since you must use `From` to construct it. It might be nice to provide a `from_u8` const constructor for users that need it.

**Comment by hdevalence** [comment]
Can we make the `From` impl a `const fn`?

**Comment by hdevalence** [comment]
I'm not totally clear on the details but from https://varkor.github.io/blog/2019/01/11/const-types-traits-and-implementations-in-Rust.html it looks like it may be possible to just declare the `From` impl we have to be `const`.

**Comment by ebfull** [comment]
In the future it will be possible to do this, yes, but I'm not optimistic about the timeframe. It's worth considering a temporary solution that can be deprecated later.

**Comment by hdevalence** [comment]
Ah, sorry, I misunderstood the blog post I linked -- I thought it was talking about the current design and not a future expansion.  If you have a usecase for constructing const Choices, we could think about adding a `from_const_u8` with a warning-of-future-deprecation.

**Comment by ebfull** [comment]
In some of my code I have structures which contain a `Choice` to indicate something about the value, but when they contain a `Choice` I cannot create constant values for the structure anymore.

**Comment by hdevalence** [comment]
I would be happy to add a `from_const_u8` with a doc comment noting the potential for future deprecation if that PR existed, but I would prefer to close this issue as "resolved discussion" until then :)
