### ISSUE TITLE
Why is there no From<bool> for Choice?

### ISSUE THREAD

**Issue by nickray** [dalek-cryptography/subtle#57]
In an abstract situation, I am more likely to come up with a bool (e.g. `number != 0`) that I would like to turn into a `Choice`, rather than a `u8`.

**Comment by hdevalence** [comment]
Hmm, our experience is that normally the opposite is the case – the condition flags used to construct a `Choice` come out of constant-time formulas, rather than equality checks which usually don't work in constant time.

**Comment by nickray** [comment]
That's a good argument. Although, as evidenced by the debug assertions, the actual `u8`s are just 0/1, so in the "isomorphic subset" where u8 and bool are the same. In this sense, I still prefer "bool" which expresses "octet with all zeros except at bit 0". But as you mention, converting a primitive integer to bool via `!= 0` (as clippy recommends) is not constant-time - one would have to do some kind of transmute instead I assume? Will have to think more about this one.

**Comment by nickray** [comment]
Anyway, closing as no longer relevant.
Pity booleans are a nice abstraction but unsafe to use in this context.
Thanks for the explanations!
