### ISSUE TITLE
Exposing constant-time `is_zero`?

### ISSUE THREAD

**Issue by gendx** [dalek-cryptography/subtle#64]
Given that the `ct_eq` implementations are currently implemented as an `is_zero` under the hood (by xor-ing the compared values), would it make sense to expose an `ct_is_zero` method in the `ConstantTimeEq` trait? Some implementations could then derive `ct_eq` from `ct_is_zero`.

If one needs to check whether a value is zero, it should be more efficient to do directly with an `ct_is_zero` method rather than constructing a temporary zero value for the purpose of comparing it.

**Comment by hdevalence** [comment]
Is there a use-case for this where constructing a temporary zero value is performance critical?

**Comment by isislovecruft** [comment]
Closing because I don't see how/where this would fail to provide a better API or better performance than doing ct_eq with a zero array.

**Comment by gendx** [comment]
> Closing because I don't see how/where this would fail to provide a better API or better performance than doing ct_eq with a zero array.

This still requires to provide an additional (zeroed) array, which means more memory consumption, which can be of non-trivial importance on embedded devices. Unless that zeroed array is optimized away, but wouldn't such optimizations contradict the very concept of constant-time traits (which aim at suppressing any compiler optimization)?
