### ISSUE TITLE
Outdated code in https://doc.dalek.rs/src/ ?

### ISSUE THREAD

**Issue by gendx** [dalek-cryptography/subtle#65]
When looking at https://doc.dalek.rs/src/subtle/lib.rs.html (linked from the "docs" badge in the README), the code seems quite outdated compared to the GitHub repository. For example, the implementation of `ct_eq` computes the and of all the bits, which was changed 4 months ago to a shorter & more efficient implementation in https://github.com/dalek-cryptography/subtle/commit/92451beb3da3174dd4f9cb166ddccb22de8b8e1c.

The version referenced in the Cargo.toml snippet at https://doc.dalek.rs/subtle/ is also 2.1 whereas there has already been multiple 2.2.x versions.

On the contrary, https://docs.rs/subtle/ generated by https://crates.io/crates/subtle is always pointing to the latest version of the library. Does it make sense to duplicate documentation in https://doc.dalek.rs/ given that docs.rs is automatically up-to-date? It's especially confusing that the "documentation" link in the header of the crates.io page differs from the "docs badge" link.

**Comment by hdevalence** [comment]
Hi, you're right that it's outdated -- the `doc.dalek.rs` site is updated by CI on the `dalek_workspace` crate, which isn't automated. There are some features that used to be missing from `docs.rs` a few years ago when this was set up; I'm not sure if it still makes sense to have independent docs hosting.

I've triggered a rebuild now; the badges could be changed to point to `docs.rs` in a PR.
