### ISSUE TITLE
should the `black_box` asm block be marked volatile?

### ISSUE THREAD

**Issue by cbeck88** [dalek-cryptography/subtle#67]
I remember watching many Chandler Carruth talks in my past life as a C++ developer. Chandler Carruth is a major contributor to llvm.

I found a choice moment from one of his talks (watch for about 1 min)

https://www.youtube.com/watch?v=nXaxk27zwlk&amp=&t=40m40s

"The two scariest tokens for the optimizer are `asm volatile`"

here's the black box function at current revision

```
/// This function is a best-effort attempt to prevent the compiler
/// from knowing anything about the value of the returned `u8`, other
/// than its type.
///
/// Uses inline asm when available, otherwise it's a no-op.
#[cfg(all(feature = "nightly", not(any(target_arch = "asmjs", target_arch = "wasm32"))))]
#[inline(always)]
fn black_box(mut input: u8) -> u8 {
    debug_assert!((input == 0u8) | (input == 1u8));

    // Move value through assembler, which is opaque to the compiler, even though we don't do anything.
    unsafe { asm!("" : "=r"(input) : "0"(input) ) }

    input
}
```

I suspect that the `asm` block should actually have the `volatile` token here for llvm to see.

Moreover, I think that this code comment:

```
    // Move value through assembler, which is opaque to the compiler, even though we don't do anything.
```

is not correct -- the compiler CAN pull out your inline assembly and start optimizing it, UNLESS you mark it `volatile`. This is based largely on my understanding of Chandler Carruth's talks, and informal discussions with my boss at my previous job who had earlier been a core developer of clang and a major contributor to llvm.

Note that, I am not an expert on compilers or llvm, and I'm not claiming to be one, but I wonder if you would be interested in a patch to make this like:

```
    unsafe { asm!("" : "=r"(input) : "0"(input) : : "volatile" ) }
```

or if you know a good reason not to do this, cause then I would learn something :)

**Comment by cbeck88** [comment]
I guess this part, 4 min later, is maybe more relevant: https://www.youtube.com/watch?v=nXaxk27zwlk&amp=&t=44m2s

**Comment by elichai** [comment]
I'm pretty sure the black_box here is based on the implementation from libcore: https://github.com/rust-lang/rust/blob/342c5f33d097b2dc07a2dbc0ca45a37379d2ff60/src/libcore/hint.rs#L109
So feel free to also comment on the related tracking issue: https://github.com/rust-lang/rust/issues/50297

**Comment by elichai** [comment]
It looks to me that right now it doesn't really matter. but it might matter more in the future? I don't know enough about llvm to answer that.
https://godbolt.org/z/D3j7rf

**Comment by cbeck88** [comment]
I was reading the gcc asm docs, it says this: (https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Volatile) on the first line

> GCC’s optimizers sometimes discard asm statements if they determine there is no need for the output variables. Also, the optimizers may move code out of loops if they believe that the code will always return the same result (i.e. none of its input values change between calls). Using the volatile qualifier disables these optimizations. asm statements that have no output operands, including asm goto statements, are implicitly volatile.

So maybe the statement is implicitly volatile because it has no output operands?

**Comment by cbeck88** [comment]
closing, thank you!
