### ISSUE TITLE
Conversions between CtOption and Option

### ISSUE THREAD

**Issue by tarcieri** [dalek-cryptography/subtle#73]
(I believe @str4d originally suggested this)

When implementing functions that don't need to be constant time (i.e. that work on public values), but when doing so using functions which are designed to work on values that are potentially secret and therefore return `CtOption`, it'd be nice to be able to explicitly opt into a `CtOption` -> `Option` conversion within the non-constant-time code.

I'd suggest adding a `From<CtOption<_>> for Option` impl similar to the existing `Choice` -> `bool` conversion for these cases.

**Comment by hdevalence** [comment]
Yup, this is a hole in the existing API.
