### ISSUE TITLE
Subtle2.3.0 cannot be compiled on my machine

### ISSUE THREAD

**Issue by Fancyflame** [dalek-cryptography/subtle#77]
This error occurred when I try to complile blake2 on Termux on my Android device:
![IMG_20201102_213331](https://user-images.githubusercontent.com/31250625/97873847-25498b80-1d53-11eb-993c-39eecc743452.png)
I think there is nothing wrong with my device because I can compile other crates successfully, maybe this is a bug?

**Comment by hdevalence** [comment]
`subtle` requires [Rust 1.41](https://github.com/dalek-cryptography/subtle#minimum-supported-rust-version), which relaxed the restrictions on orphan rules to make the trait impls we need possible.  So, if you're using a Rust older than 1.41, updating your Rust should fix this problem.

**Comment by Fancyflame** [comment]
> `subtle` requires [Rust 1.41](https://github.com/dalek-cryptography/subtle#minimum-supported-rust-version), which relaxed the restrictions on orphan rules to make the trait impls we need possible. So, if you're using a Rust older than 1.41, updating your Rust should fix this problem.

I see, but unfortunately the highest version I could have on Android is rust 1.38.0, so I still have no idea about how to compile it on my device. But your comment helped me awared this, thanks a lot.

**Comment by hdevalence** [comment]
@Fancyflame subtle `2.2.x` has a different MSRV policy, so you may be able to work around this issue by pinning `subtle` to `2.2.x` rather than `2.3.0`.

**Comment by isislovecruft** [comment]
@Fancyflame If you installed your rust compiler with `curl https://sh.rustup.rs -sSf | sh` and added the targets for android with `rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android` then all the versions available to other targets should be available for android as well, and you can upgrade by doing `rustup update`.

**Comment by Fancyflame** [comment]
I know that, but rustup cannot install host for android neither because there is no host triple for android yet (probably it is because few would developing projects on Android device). I have solved this by installing a tiny Ubuntu in Termux and install rust in it. Rust and Subtle now can run in the tiny Ubuntu perfectly. :)

**Comment by Fancyflame** [comment]
@isislovecruft I know that, but I mean I use Rust on my android device, and rustup cannot install host for android neither because there is no host triple for android yet (probably it is because few would developing projects on Android device). I have solved this by installing a tiny Ubuntu in Termux and install rust in it. Rust and Subtle now can run in the tiny Ubuntu perfectly. :)
