### ISSUE TITLE
Ensuring `no_std` for subtle 

### ISSUE THREAD

**Issue by mustermeiszer** [dalek-cryptography/subtle#88]
Hello, 

first of all, I am not sure if this is a bug or something that results from my bad understanding of rusts `no_std` environments, so please bear with me.
If I understand it correctly `subtle` is meant to work in `no_std` envs. If not, this issue can be closed. 

*Problem Description*
I have `subtle` as a transitive dependency in my project, namely from the `schnorrkel` crate that I use. When I am compiling my project I get the following error:

```shell
  Blocking waiting for file lock on package cache
     Compiling sp-io v4.0.0-dev (https://github.com/centrifuge/substrate?branch=master#32b0fa55)
  error[E0152]: found duplicate lang item `panic_impl`
      --> /Users/frederik/.cargo/git/checkouts/substrate-c08550cb428dbcc9/32b0fa5/primitives/io/src/lib.rs:1424:1
       |
  1424 | pub fn panic(info: &core::panic::PanicInfo) -> ! {
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: the lang item is first defined in crate `std` (which `subtle` depends on)
       = note: first definition in `std` loaded from /Users/frederik/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-17199824ef310338.rlib
       = note: second definition in the local crate (`sp_io`)

  error[E0152]: found duplicate lang item `oom`
      --> /Users/frederik/.cargo/git/checkouts/substrate-c08550cb428dbcc9/32b0fa5/primitives/io/src/lib.rs:1435:1
       |
  1435 | pub fn oom(_: core::alloc::Layout) -> ! {
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: the lang item is first defined in crate `std` (which `subtle` depends on)
       = note: first definition in `std` loaded from /Users/frederik/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-17199824ef310338.rlib
       = note: second definition in the local crate (`sp_io`)

  For more information about this error, try `rustc --explain E0152`.
  error: could not compile `sp-io` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

This error led me to the conclusion that `subtle` for some reason integrates rusts `std` lib.

Can you help me out, if this could be the case? So far my research only showed me that rust's compiler is not able to detect `no_std` incompatibilities in dependencies [here](https://blog.dbrgn.ch/2019/12/24/testing-for-no-std-compatibility). Although, I am not aware if this is still the case. 

Thank you in advance for your help!

**Comment by AnomalRoil** [comment]
How did you compile your project exactly?
`std` is a default feature of `subtle`, so you should be using `cargo build --no-default-features` to avoid it.

Just like curve25519-dalek (which relies on subtle) doc says:
> The std feature is enabled by default, but it can be disabled for no-std builds using --no-default-features

**Comment by mustermeiszer** [comment]
I am building with my feature `runtime-benchmarks` which is defined like: 

`runtime-benchmarks = ["frame-benchmarking", "sp-core/full_crypto", "substrate-bip39", "schnorrkel"]`

and `schnorrkel` is integrate like `schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false, optional = true }`.

**Comment by mustermeiszer** [comment]
Sorry. Exact compilation command is: `cargo +nightly run --release --features runtime-benchmarks -- ...`

**Comment by mustermeiszer** [comment]
I am closing this. I found the issue. `substrate-bip39` is integrating `schnorrkel` with default-features. Thanks for your time!
