### ISSUE TITLE
Alternative license

### ISSUE THREAD

**Issue by cmcqueen** [dalek-cryptography/subtle#92]
I am working on a project that has a policy to avoid BSD 2- and 3-clause licenses due to the complexity of satisfying the attribution clause:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

Would you consider dual-licensing this project? Eg with MIT and/or Apache 2.0 licenses?

**Comment by isislovecruft** [comment]
MIT and Apache 2.0 both also require redistributions to include the copyright notice. There are no legitimate FOSS licences to my knowledge which allow a downstream consumer to disregard and forsake informing users of the upstream licence.
